---
# tasks file for ocp4-post-costmanagement
- name: '[POSTINSTALL][COSTMANAGEMENT] Create Namespace'
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present    
    definition: "{{ lookup('template', 'costmanagement-namespace.yaml') }}"
  
  
- name: '[POSTINSTALL][COSTMANAGEMENT] Create Operator Group'
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('file', 'costmanagement-operator-group.yaml') }}"

- name: [POSTINSTALL][COSTMANAGEMENT] Subscribing to OCP metering
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'costmanagement-subscription.yaml') }}"    
