---

- import_tasks: download.yml

- import_tasks: create_config.yml

- import_tasks: install.yml

- import_tasks: print_info.yml

#- import_tasks: uninstall.yaml
#  when:
#    - uninstall_ocp is defined
